{"uuid": "22fd7832-0f79-4a02-aade-ba988c2ed29c", "children": ["d1be6161-aa10-447d-89c5-1d92a0b7105b", "e27dc5e5-c5cf-4e3b-bf88-57eb97d2d8e7"], "befores": [{"name": "list_ingredient", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stellarburgers.nomoreparties.site', port=443): Max retries exceeded with url: /api/ingredients (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x0000020433EDFF70>: Failed to resolve 'stellarburgers.nomoreparties.site' ([Errno 11001] getaddrinfo failed)\"))\n", "trace": "  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\kuturma\\Desktop\\Diplom_2_develop2\\tests\\conftest.py\", line 68, in list_ingredient\n    response = requests.get(TestEndpoint.INGREDIENTS)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1753258706478, "stop": 1753258706480}], "start": 1753258706478, "stop": 1753258706622}