{"uuid": "6df87607-e7e6-4e5e-99b8-4a61a26ba4ef", "children": ["2c603fdd-cef6-4a3c-a232-1a08d08abaf9", "6a2fac29-889c-4a9a-bb31-672d7c86dad5"], "befores": [{"name": "list_ingredient", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stellarburgers.nomoreparties.site', port=443): Max retries exceeded with url: /api/ingredients (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x000001C4CB13FAF0>: Failed to resolve 'stellarburgers.nomoreparties.site' ([Errno 11001] getaddrinfo failed)\"))\n", "trace": "  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 898, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\kuturma\\Desktop\\Diplom_2_develop2\\tests\\conftest.py\", line 68, in list_ingredient\n    response = requests.get(TestEndpoint.INGREDIENTS)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"C:\\Users\\kuturma\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\requests\\adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1753258782586, "stop": 1753258782588}], "start": 1753258782586, "stop": 1753258782727}